name: Build spec as HTML

on:
  pull_request:
    paths:
      - 'publish/**'
      - 'spec/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: make dist/index.html
        working-directory: ./publish
